### ISSUE TITLE
Add more STAC tools

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-site#23]
There's at least a few more tools to add:

* Staccato - Java STAC API
* intake stac (or stac intake?) Need to find the link
* [Lite-stac](https://github.com/tonybutzer/lite-stac)

I think there's some more out there, if anyone has them just add to this ticket.

**Comment by cholmes** [comment]
Also RasterFoundry, looks like it's got some decent STAC support now.

**Comment by HamedAlemo** [comment]
* This is [intake-stac](https://github.com/pangeo-data/intake-stac)
* Also [stac-validator](https://github.com/sparkgeo/stac-validator)

**Comment by cholmes** [comment]
Also https://github.com/jjrom/resto
https://github.com/syncarto/stac-gen
https://github.com/azavea/pystac
Astraea's earth on demand server
Harris's work

**Comment by stuartpearman** [comment]
New website will pull directly from stacindex.org/ecosystem
