### ISSUE TITLE
Update implementations

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-site#29]
STAC in action and STAC Tools could both use updates to capture the state of the community. We should try to link to more live catalogs, and to link to the json catalog in addition to the stac browser.

**Comment by cholmes** [comment]
Be sure to add pygeoapi as well - https://github.com/radiantearth/stac-spec/pull/765/

**Comment by m-mohr** [comment]
@cholmes Already done!

**Comment by cholmes** [comment]
Oh nice! I checked open issues but forgot to check closed PR's. Thanks!
