### ISSUE TITLE
Add Microsoft to STAC Companies

### ISSUE THREAD

**Issue by brunosan** [radiantearth/stac-site#38]
Microsoft is sponsor for the STAC sprint. I think we should its logo to [image](https://github.com/radiantearth/stac-site/blob/master/images/STAC_companies.png) in the front page.

I can't find the individual logos, so I'll add the Microsoft logo to the image above and PR

**Comment by m-mohr** [comment]
In general, this will come up more and more so I guess we should start adding either individual images or just list the companies with textual links... @cholmes
