### ISSUE TITLE
Recent changes not appearing on site

### ISSUE THREAD

**Issue by gadomski** [radiantearth/stac-site#48]
E.g. e9efdb2c26173e51a15f58e1be80f78916515380 from Feb 1, which fixed the STAC API link on index.html, is not propagating to the public site:

<img width="716" alt="Screen Shot 2021-03-09 at 9 15 43 AM" src="https://user-images.githubusercontent.com/58314/110502026-091a7a00-80b8-11eb-838f-016ec6188d14.png">

**Comment by cholmes** [comment]
Hrm, weird. Will try to dig into this. Thanks for reporting.

**Comment by gadomski** [comment]
Worksforme!
