### ISSUE TITLE
Update link to API spec

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-site#53]
The link from the stacspec.org homepage goes to https://stacspec.org/STAC-api.html instead of https://api.stacspec.org/v1.0.0-beta.3/

We should fix that. And is there a 'latest' place we can point it, so we don't have to update the website at every release?

**Comment by m-mohr** [comment]
Can we redirect the old links to latest?

**Comment by m-mohr** [comment]
@pieschker Should https://api.stacspec.org/ list and link to all versions available?
