### ISSUE TITLE
"How to help" links to localhost

### ISSUE THREAD

**Issue by frafra** [radiantearth/stac-site#65]
"How to Help" in https://stacspec.org/en/get-involved/data-users/ links to http://localhost:8080/en/get-involved/.

**Comment by jedsundwall** [comment]
Fixed with https://github.com/radiantearth/stac-site/commit/bd93be933ec150f88d66befeb2057c4d7fab7116

**Comment by jedsundwall** [comment]
This has been deployed: https://stacspec.org/en/get-involved/data-users/

**Comment by bmcandr** [comment]
The Developers and Data Providers pages also link to `localhost`:
* https://github.com/radiantearth/stac-site/blob/main/content/get-involved/developers.js#L58
* https://github.com/radiantearth/stac-site/blob/main/content/get-involved/data-providers.js#L40

**Comment by PowerChell** [comment]
@bmcandr thanks for catching this; i will update it right now!

**Comment by PowerChell** [comment]
@bmcandr @frafra fixed in #71 🎉
